version: '3.8'

services:
  # Node.js App
  # Service 1: The Static Frontend
  frontend:
    build: ./services/frontend
    container_name: micro-frontend
    restart: always
    ports:
      # Maps Host Port 8080 -> Container Port 80
      - "127.0.0.1:8080:80"
    networks:
      - app-network

  # Service 2: The API Backend
  backend:
    build: ./services/backend
    container_name: micro-backend
    restart: always
    ports:
      # Maps Host Port 3000 -> Container Port 3000
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Node Exporter
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "127.0.0.1:9100:9100"

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:

# Create a custom network so services can talk to each other
networks:
  app-network:
    driver: bridge